### ISSUE TITLE
some commands no longer work since the last set of merges

### ISSUE THREAD

**Issue by MarshallAsch** [SoorajModi/Botomir#32]
I think all was working in the separate branch and I suspect that there may have been an unresolved merge conflict or some other config issue.

**Comment by SoorajModi** [comment]
Which commands?

**Comment by SoorajModi** [comment]
help command does not work

**Comment by MarshallAsch** [comment]
@SoorajModi  is this still an issue? it seemed to magically start working again.

**Comment by SoorajModi** [comment]
Nope, seems to be working now, not sure why it wasnt working before
