### ISSUE TITLE
MongoDB Atlas Tier

### ISSUE THREAD

**Issue by SoorajModi** [SoorajModi/Botomir#66]
> Add details about Botomir's statistics on the website, ie. number of servers, number of messages, number of total users

I was looking into mongo queries that will make cool graphs such as aggregateing the number of messages per day / hour and stuff like that and we can not do a query like:
`db.messages.aggregate([{date: {'$dateToString': {format: '%Y-%m-%d', date: '$timestamp'}}}, {$group: { _id: {date: '$date'}, count: {$sum:1 } }}])`

(That is a mongo query not a mongoose one)

and it fails with this error:
```
 E QUERY    [js] Error: command failed: {
	"ok" : 0,
	"errmsg" : "date is not allowed in this atlas tier",
	"code" : 8000,
	"codeName" : "AtlasError"
} : aggregate failed :
```

Is that something that we would be able to fix by tossing some credits at the server to bump it to a different tier or do you think we would just be out of luck for that?

or something like `Message.aggregate([{$group: { _id: {author: '$author'}, count: {$sum:1 } }}]).then(r => console.log(r)).catch(e=>console.log(e));` for mongoose

_Originally posted by @MarshallAsch in https://github.com/SoorajModi/Botomir/issues/37#issuecomment-785113531_

**Comment by SoorajModi** [comment]
Find out what atlas tier we need to enable this

**Comment by MarshallAsch** [comment]
Upon further investigation the of the limitations of the Mongo Atlas Cloud:
"M0 Free Tier and M2/M5 shared clusters do not support server-side JavaScript." [¹]


This means the only available option is to use a M10 tier which costs way to much money for this to be used. Alternatively we could self host the DB instance somwhere else.

[¹]: https://docs.atlas.mongodb.com/reference/free-shared-limitations/

**Comment by MarshallAsch** [comment]
The free tier of Mlabs https://mlab.com/plans/pricing/#plan-type=sandbox might be able to support server side JavaScript. It has the same amount of storage space as the atlas m0 tier
