### ISSUE TITLE
Add support for role add/remove with name of role in text instead of @role

### ISSUE THREAD

**Issue by SoorajModi** [SoorajModi/Botomir#7]

**Comment by SoorajModi** [comment]
Ie. instead !role @keeb, it should be !role keeb

**Comment by MarshallAsch** [comment]
Should this work for both `!role keeb` and `!role @keeb` or only without the `@`?

**Comment by SoorajModi** [comment]
Just `!role keeb` to avoid confusing the user and keep things simple
