### ISSUE TITLE
Add a contributing doc

### ISSUE THREAD

**Issue by SoorajModi** [SoorajModi/Botomir#71]
Add a document to indicate rules for contributing so other friends can also help out with the project

- [x] Include information about Discord.js and how to get started
- [x] Include instructions on what to include in a PR

**Comment by SoorajModi** [comment]
Includes these links:
- https://discordjs.guide/
- https://discord.js.org/#/docs/main/stable/general/welcome

**Comment by SoorajModi** [comment]
PRs should include
- summary of what was changed and why (the second part less so, more for big or odd things)
- how it was tested
- what should be tested
- any oddness or funky behaviour that might come up again later or where extra attention should be given during a review
- breaking changes

**Comment by MarshallAsch** [comment]
This can also include the addition of issue templates and a PR template that includes some of that info. I love the templates we use them in [liquidctl](https://github.com/liquidctl/liquidctl) and them make user submitted issues much easier to deal with.
