### ISSUE TITLE
Role assignment/removal fails but success message is sent

### ISSUE THREAD

**Issue by SoorajModi** [SoorajModi/Botomir#84]
If a user calls `role`, `give`, `remove`, or `revoke` commands on a role lower than Botomir on the role hierarchy, Botomir will send a success message, indicating the action succeeded, however the action failed.

How to reproduce:
- Create role and place it higher on the hierarchy than the `Botomir` role
- Call the command `!role name_of_role`
- Botomir will respond with a success message
- Role will not actually be assigned to self

Botomir should send a failure message letting the user know about the issue with role hierarchies.

**Comment by MarshallAsch** [comment]
I had through there was a check in the role assignment code that checked if the bot is able to manage the role

**Comment by SoorajModi** [comment]
I thought so too, but it seems to still be an issue

On a side note, we should also make privileged roles configurable by the user
