### ISSUE TITLE
Flip and roll command proposal 

### ISSUE THREAD

**Issue by SoorajModi** [SoorajModi/Botomir#95]
- Describe the feature in as much detail as possible
   - `!flip` will result in either heads or tails
   - `!roll <number>` returns a random number from 1 to number
- Explain why you would like this feature
  - Nice utility feature that will be useful if the user needs to roll a die or flip a coin
- State a use case for this feature
  - As a user I want to flip a coin so that I dont have to in real life
  - As a user I want to roll a die when i need to randomly generate a number
- Number of arguments for the command
  - flip, no arguments
  - roll, 1 argument, number of heads on die
- Name of the command
  - flip
  - roll
- If it will require the Botomir Admin role to execute
  - no
- A description of the command
  - flips a coin
  - rolls a die
- All aliases
  - n/a

**Comment by MarshallAsch** [comment]
how were you thinking of generating random numbers for this. (don't say `math.random()` because that is not a real random value)

**Comment by SoorajModi** [comment]
We have the power of open source!

Will prob use an npm package like [borand](https://www.npmjs.com/package/brorand) or [pure random number](https://www.npmjs.com/package/pure-random-number)

**Comment by MarshallAsch** [comment]
> Will prob use an npm package like  [borand] or [pure random number].

Just as a note for later those are bot cryptographically secure _psudo_ random number generators, not true random number generators, therefore technically not fit to be used for this purpose. 


[borand]: https://www.npmjs.com/package/brorand
[pure random number]: https://www.npmjs.com/package/pure-random-number
